# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Toby Bloem
email: toby@tobybloem.com
description: > # this means to ignore newlines until "baseurl:"
  Professional site for Software Engineer/Web Developer Toby Bloem
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tobybloem.com" # the base hostname & protocol for your site
twitter_username: TobyBloem
github_username:  tobybloem

# Build settings
markdown: kramdown
